#!/bin/bash
#Amazon Linux 2 Kernel 5.10 AMI 2.0.20220426.0 x86_64 HVM gp2
#ami-0fa49cc9dc8d62c84


sudo yum update -y
sudo yum install httpd.x86_64 -y
sudo service httpd start
sudo systemctl enable httpd
sudo yum install unzip -y
sudo yum install ruby.x86_64 -y
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
cd /home/ec2-user/
wget https://aws-codedeploy-us-east-2.s3.us-east-2.amazonaws.com/latest/install
chmod +x ./install
sudo ./install auto